apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: git-action
  namespace: git-action

commonLabels:
  app: git-action

resources:
- sensor-rbac.yaml
- webhook.yaml
- special-workflow-trigger-shortened.yaml
- eventbus/native.yaml