apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: git-action

commonLabels:
  app: git-action

resources:
- sensor-rbac.yaml
- webhook.yaml
- git-action-workflow-submit.yaml
- eventbus/native.yaml