apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: iws
servers: 1
options:
  k3d:
    disableLoadbalancer: false
  k3s:
    extraArgs:
      - arg: "--disable=traefik"
        nodeFilters:
          - server:0
registries: # define how registries should be created or used
  create: # creates a default registry to be used with the cluster; same as `--registry-create registry.localhost`
    name: registry.localhost
    host: "0.0.0.0"
    hostPort: "5000"
ports:
  - port: 31120:31120 # same as `--port '8080:80@loadbalancer'`
    nodeFilters:
      - server:0