apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io/foreground
  name: argo-ingress
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: default
  source:
    path: ./cloud-components/kustomize/argocd
    repoURL: https://github.com/intellizone/code-ecosystem.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}