apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
- ../base

configMapGenerator:
- name: readinglist-ui-config
  envs:
  - configmap.yaml

generatorOptions:
  disableNameSuffixHash: false

patches:
- target:
    kind: VirtualService
    name: readinglist-ui
  patch: |-
    - op: replace
      path: /spec/hosts/0
      value: readinglist-dev.localhost
- target:
    kind: Gateway
    name: readinglist-ui
  patch: |-
    - op: replace
      path: /spec/servers/0/hosts/0
      value: readinglist-dev.localhost

replacements:
- source:
    kind: ConfigMap
    name: readinglist-ui-config
    fieldPath: data.VERSION
  targets:
  - select:
      kind: Deployment
      name: readinglist-ui
    fieldPaths: 
    - spec.template.spec.containers.[name=readinglist-ui].image
    options:
      delimiter: ":"
      index: 2