apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: readinglist-ui
  namespace: dev

commonLabels:
  app: readinglist-ui
resources:
- deployment.yaml
- namespace.yaml
- service.yaml
- vs.yaml
- gw.yaml